"""
Project FORESIGHT — D6 Scoring Service
======================================
A read-only FastAPI service that exposes the existing production forecast
and risk outputs for a SKU (or a batch of SKUs).

This service does NOT recompute forecasting or risk logic. It serves the
artifacts already produced by:
    src/pipeline.py  ->  data/processed/
    notebooks/02,03  ->  data/processed/forecast_output.csv
    src/risk.py      ->  data/processed/risk_output.csv

Run locally:
    uvicorn service.main:app --reload --port 8000
Docs:
    http://localhost:8000/docs
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Paths (repo-relative, deployment friendly)
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
PROCESSED_DIR = ROOT / "data" / "processed"
REPORTS_DIR = ROOT / "reports"

RISK_FP = PROCESSED_DIR / "risk_output.csv"
FORECAST_FP = PROCESSED_DIR / "forecast_output.csv"
FORECAST_METRICS_FP = REPORTS_DIR / "forecast_metrics.csv"

FORECAST_HORIZON_WEEKS = 6  # matches the production forecast horizon
MAX_BATCH_SIZE = 200

app = FastAPI(
    title="FORESIGHT Scoring Service",
    description=(
        "Returns the production demand forecast and inventory risk assessment for a SKU.\n\n"
        "**Production forecast:** Seasonal-Naive baseline (6-week horizon). The evaluated "
        "gradient-boosting model did not outperform the baseline on backtest and is not used "
        "for any decision returned here.\n\n"
        "This service is read-only: it serves the artifacts generated by `src/pipeline.py`, "
        "the forecasting notebooks and `src/risk.py`. It does not recompute any model or risk logic."
    ),
    version="1.0.0",
)


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------
class ForecastWeek(BaseModel):
    week: str = Field(..., description="Forecast week start date (YYYY-MM-DD).", examples=["2026-01-05"])
    predicted_demand: float = Field(..., description="Predicted units for that week.", examples=[100.0])


class SKUScore(BaseModel):
    SKU: str = Field(..., examples=["SKU012"])
    Product_Name: str | None = Field(None, examples=["Product 012"])
    Category: str | None = Field(None, examples=["Home Decor"])

    forecast_horizon_weeks: int = Field(..., description="Forecast horizon in weeks.", examples=[6])
    forecast_model: str | None = Field(None, description="Model used for the production forecast.",
                                        examples=["Seasonal-Naive Baseline"])
    forecast_demand_total: float | None = Field(
        None, description="Total predicted demand over the forecast horizon (units).", examples=[1135.0])
    forecast_weekly: list[ForecastWeek] = Field(
        default_factory=list, description="Week-by-week production forecast.")

    stockout_risk: bool | None = Field(None, examples=[True])
    overstock_risk: bool | None = Field(None, examples=[False])
    risk_action: str | None = Field(
        None, description="REORDER NOW | MARKDOWN / CLEAR | WATCH / VOLATILE | HEALTHY",
        examples=["REORDER NOW"])

    sales_at_risk_rs: float | None = Field(None, description="Estimated sales exposure (INR).",
                                            examples=[2484561.71])
    capital_locked_rs: float | None = Field(None, description="Estimated locked capital (INR).", examples=[0.0])
    total_rupee_impact_rs: float | None = Field(None, description="Estimated total exposure (INR).",
                                                 examples=[2484561.71])
    priority_score: float | None = Field(None, description="Higher means more urgent.", examples=[17.65])


class BatchScoreRequest(BaseModel):
    skus: list[str] = Field(
        ..., min_length=1, max_length=MAX_BATCH_SIZE,
        description=f"List of SKU identifiers to score (1-{MAX_BATCH_SIZE}).",
        examples=[["SKU012", "SKU025", "SKU009"]],
    )


class BatchScoreResponse(BaseModel):
    requested: int = Field(..., description="Number of SKUs requested.")
    found: int = Field(..., description="Number of SKUs successfully scored.")
    not_found: list[str] = Field(default_factory=list, description="Requested SKUs with no data.")
    results: list[SKUScore] = Field(default_factory=list)


class HealthResponse(BaseModel):
    status: str = Field(..., examples=["ok"])
    scored_skus: int = Field(..., description="Number of SKUs available for scoring.")
    forecast_horizon_weeks: int
    production_model: str | None = None
    data_sources: dict[str, bool] = Field(..., description="Whether each required artifact was found.")


# ---------------------------------------------------------------------------
# Data access (cached at process start; artifacts are static files)
# ---------------------------------------------------------------------------
@lru_cache(maxsize=1)
def load_risk() -> pd.DataFrame:
    if not RISK_FP.exists():
        return pd.DataFrame()
    df = pd.read_csv(RISK_FP)
    df["SKU"] = df["SKU"].astype(str).str.strip().str.upper()
    return df.drop_duplicates(subset=["SKU"])


@lru_cache(maxsize=1)
def load_forecast() -> pd.DataFrame:
    if not FORECAST_FP.exists():
        return pd.DataFrame()
    df = pd.read_csv(FORECAST_FP, parse_dates=["forecast_week"])
    df["SKU"] = df["SKU"].astype(str).str.strip().str.upper()
    return df.sort_values(["SKU", "forecast_week"])


@lru_cache(maxsize=1)
def production_model_name() -> str | None:
    fc = load_forecast()
    if not fc.empty and "selected_model" in fc.columns:
        return str(fc["selected_model"].iloc[0])
    return None


@lru_cache(maxsize=1)
def known_skus() -> frozenset[str]:
    skus: set[str] = set()
    risk, fc = load_risk(), load_forecast()
    if not risk.empty:
        skus |= set(risk["SKU"])
    if not fc.empty:
        skus |= set(fc["SKU"])
    return frozenset(skus)


def _clean(value):
    """Convert numpy/pandas scalars to plain Python, mapping NaN to None."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return None
    if pd.api.types.is_scalar(value) and pd.isna(value):
        return None
    if hasattr(value, "item"):
        return value.item()
    return value


def build_score(sku: str) -> SKUScore | None:
    """Assemble the response for one SKU from the existing outputs. Returns None if unknown."""
    sku = sku.strip().upper()
    if sku not in known_skus():
        return None

    risk, fc = load_risk(), load_forecast()

    risk_row = None
    if not risk.empty:
        match = risk[risk["SKU"] == sku]
        if not match.empty:
            risk_row = match.iloc[0]

    fc_rows = fc[fc["SKU"] == sku] if not fc.empty else pd.DataFrame()

    weekly = [
        ForecastWeek(week=r["forecast_week"].strftime("%Y-%m-%d"),
                     predicted_demand=float(r["predicted_demand"]))
        for _, r in fc_rows.iterrows()
    ]

    # Prefer the risk engine's own horizon total so the API never disagrees with risk_output.csv.
    if risk_row is not None and not pd.isna(risk_row.get("forward_demand_6w")):
        demand_total = float(risk_row["forward_demand_6w"])
    elif not fc_rows.empty:
        demand_total = float(fc_rows["predicted_demand"].sum())
    else:
        demand_total = None

    def rv(col):
        return _clean(risk_row[col]) if risk_row is not None and col in risk_row.index else None

    return SKUScore(
        SKU=sku,
        Product_Name=rv("Product_Name"),
        Category=rv("Category"),
        forecast_horizon_weeks=FORECAST_HORIZON_WEEKS,
        forecast_model=production_model_name(),
        forecast_demand_total=demand_total,
        forecast_weekly=weekly,
        stockout_risk=bool(risk_row["stockout_risk"]) if risk_row is not None else None,
        overstock_risk=bool(risk_row["overstock_risk"]) if risk_row is not None else None,
        risk_action=rv("risk_action"),
        sales_at_risk_rs=rv("sales_at_risk_rs"),
        capital_locked_rs=rv("capital_locked_rs"),
        total_rupee_impact_rs=rv("total_rupee_impact_rs"),
        priority_score=rv("priority_score"),
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.get("/health", response_model=HealthResponse, tags=["System"],
         summary="Service health and data availability")
def health() -> HealthResponse:
    return HealthResponse(
        status="ok",
        scored_skus=len(known_skus()),
        forecast_horizon_weeks=FORECAST_HORIZON_WEEKS,
        production_model=production_model_name(),
        data_sources={
            "risk_output.csv": RISK_FP.exists(),
            "forecast_output.csv": FORECAST_FP.exists(),
            "forecast_metrics.csv": FORECAST_METRICS_FP.exists(),
        },
    )


@app.get("/score/{sku}", response_model=SKUScore, tags=["Scoring"],
         summary="Forecast and risk for a single SKU",
         responses={404: {"description": "SKU not found in the modeled set."}})
def score_sku(sku: str) -> SKUScore:
    result = build_score(sku)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(f"SKU '{sku}' not found. Only the {len(known_skus())} modeled SKUs "
                    f"(with both sales and product-master history) can be scored."),
        )
    return result


@app.post("/score", response_model=BatchScoreResponse, tags=["Scoring"],
          summary="Forecast and risk for a batch of SKUs")
def score_batch(payload: BatchScoreRequest) -> BatchScoreResponse:
    results, not_found = [], []
    for sku in payload.skus:
        scored = build_score(sku)
        if scored is None:
            not_found.append(sku)
        else:
            results.append(scored)
    return BatchScoreResponse(
        requested=len(payload.skus),
        found=len(results),
        not_found=not_found,
        results=results,
    )


@app.get("/", include_in_schema=False)
def root() -> JSONResponse:
    return JSONResponse({
        "service": "FORESIGHT Scoring Service",
        "docs": "/docs",
        "endpoints": ["/health", "/score/{sku}", "POST /score"],
    })
